accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name= 'accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register,name='register')
]

django_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django_app import views


# custom error handler

handler404 = 'django_app.views.handler404'


# url patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('api/',include('polls.api_urls')),
    path('accounts/',include('accounts.urls')),
]

polls/urls.py
from django.urls import path
from .import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('contact/', views.contact , name='contactform'),
    
]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = "pub_date"
    was_published_recently.boolean = True
    was_published_recently.short_description = 'published recently?'

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

polls/forms.py
from django import forms
from .models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text','pub_date')

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('polls.index')
    else:
        form = UserCreationForm()
    return render(request, 'account/register.html',{'form': form})

django_app/views.py
from django.shortcuts import render

def handler404(request, exception):
    return render(request, '404.html', status=404)

# def handler500(request):
#     return render(request,'500.html', status=500)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.urls import reverse
from polls.models import Question, Choice
from .forms import ContactForm
from django.contrib.auth.decorators import login_required


@login_required #user to ensure user is logged in


# Create your views here.



def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Process the data
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            # Perform actions (e.g., send email)
            return redirect('polls:thanks')
    else:
        form = ContactForm()
    return render(request, 'polls/contact.html', {'form': form})


def index(request):
    latest_question_list = Question.objects.order_by('pub_date')
    paginator = Paginator(latest_question_list ,5)  #show 5 question per page
    page_number=paginator.get_page('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'polls/index.html',{"page_obj":page_obj})

#class base approach
from  django.views import View
from django.http import HttpResponse

# class indexview(View)
def get(self, request):
    return HttpResponse("hello world you are at the poll index")

def detail(request, question_id):
    # view to display a specific questuion
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question':question})

def results(request, question_id):
    # view to display the result of a specigic question
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question} )

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice._set_get(pk = request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render (request, 'polls/details.html',{
            'question': question,
            'error_message': "you didn't select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls.results', args=(question.id)))

accounts/templates/accounts/login.html
<!--django_app\accounts\templates\accounts\login.html-->

{%extends 'base_generic.html'%} {% block content %}
<h2>Login</h2>
<form method="post">
  {%csrf_token%} {{form.as_p}}
  <button type="submit">Login</button>
</form>
{%endblock%}

accounts/templates/accounts/register.html
{% extends "base_generic.html" %}

{%block content%}
<h2>Register</h2>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Register</button>
</form>
{%endblock%}

polls/templates/polls/contact.html
<h1>Contact Us</h1>
<form menthod="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Submit</button>
</form>

polls/templates/polls/detail.html
{% comment %} polls/template/polls/detail.html {% endcomment %}
{% extends 'base_generic.html' %}
<block title>{{question.question_text}}</endblock>

{% block content%}
<h1>{{question.question_text}}</h1>

    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {%endif%}

    <form action="{% url 'polls:vote' question.id%}" method="post">
        {%csrf_token%}
        {% for choice in question.choice_set.all%}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choise.id}}">
            <lable for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>    
        {%endfor%}
        <button type="submit" >Vote</button>
    </form>
{%endblock%}

polls/templates/polls/index.html
{% extends "base_generic.html" %} {%block title%}Polls Index{% endblock%}
{%block content%}
<h1>Polls Index</h1>
{% if page_obj %}
<ul>
  {% for question in page_obj %}
  <li>
    <a href="{%url 'polls:detail' question.id%}">{{question.question_text}}</a>
  </li>
  {% endfor %}
</ul>
<div class="pagination">
  <span class="page_links">
    {%if page_obj.has_previous%}
    <a href="?page1">&laquo; first</a>
    <a href="?page={{page.obj.previous_page_number}}">previous</a>
    {%endif%}

    <span class="current">
      page {{page_obj.number}} of {{page_obj.paginator.num_page}}
    </span>

    {% if page_obj.has_next%}
    <a href="?page={{page.obj.next_page_number}}">next</a>
    <a href="?page={{page.obj.paginator.num_number}}"> last</a>
    {%endif%}
  </span>
</div>
{%else%}
<p>No polls afe available</p>
{%endif%} {%endblock%}

polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} --  {{ choice.votes}} votes {{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>


<a href="{% url 'polls:detail' question.id%}">vote  again?</a>

templates/base_generic.html
<html>
  <head>
    <title>{% block title %}My Site{% endblock %}</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}</p>
    <form method="post" action="{% url 'accounts:logout' %}">
      {% csrf_token %}
      <button type="Submit">Logout</button>
    </form>
    {% else %}
    <p>
      <a href="{% url 'accounts:login' %}">Login</a> |
      <a href="{% url 'accounts:register' %}">Register</a>
    </p>
    {% endif %}
    {%block content%}
        
    {%endblock%}
  </body>
</html>